Download pages for different platforms
DerangedSenators/website pull request #16
Opened 2021-02-12 21:20 UTC by NoIdea050

2021-02-12 21:49 UTC, SaharBatol approved these changes
Looks good!

2021-02-13 00:39 UTC, hsravat-4590 commented on download/thankyou-for-downloading.html
> +layout: default
Should keep page over default here

2021-02-13 00:40 UTC, hsravat-4590 commented on download/linux-screen.html
> +</div>
This file should be converted to markdown and have its custom styles removed. Will be more timeless that way

2021-02-13 12:43 UTC, hsravat-4590 requested changes

2021-02-13 12:43 UTC, hsravat-4590 commented on _posts/blog/15-10-2020-Getting-Started.md
> +<br />
Dont need break tags here... If you want to space some lines, use double return instead

2021-02-13 12:43 UTC, hsravat-4590 commented on _sass/derangedsenators/download.scss
> +    font-family: "montserrat", sans-serif;
Change font-family to Roboto. This is the font that is used for the rest of the site

2021-02-13 12:43 UTC, hsravat-4590 commented on download/download-options.html
> +    <button class="btn1" type="submit"><a href=""><strong>Android</strong></a></button>
For android link to `{{site.baseurl}}/download/download/?type=standalone&platform=android`
For windows link to `{{site.baseurl}}/download/download/?type=launcher&platform=windows`
For linux link to `{{site.baseurl}}/download/download/?type=standalone&platform=linux`
For MacOS link to `{{site.baseurl}}/download/download/?type=launcher&platform=mac`
For IOS link to `{{site.baseurl}}/download/download/?type=standalone&platform=ios`

2021-02-13 12:43 UTC, hsravat-4590 commented on download/linux-screen.html
> +---
Rename to download-for-linux.md (This is what the existing page is called and the js will try to open that link)

Also remove styling and use normal markdown so that it will automatically be kept constant with any theme changes

2021-02-13 12:43 UTC, hsravat-4590 commented on download/thankyou-for-downloading.html
> +layout: default
Keep layout as page over default

2021-02-13 13:37 UTC, hsravat-4590 approved these changes
LGTM! :+1:

2021-02-13 13:37 UTC, merged